# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Parahumains
email: adam@hammes.io
description: > # this means to ignore newlines until "baseurl:"
  La traduction française du roman « Worm », par Wildbow. Les chapitres
  sortiront tels qu'ils sont traduits.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://parahumains.com" # the base hostname & protocol for your site

exclude: ['CNAME', 'scripts/', 'venv/', 'Gemfile', 'Gemfile.lock']

sass:
    style: compressed

permalink: /:title

# This option requires the jekyll_livereload gem to be installed
livereload: true

# Build settings
markdown: kramdown
